// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: files.sql

package db

import (
	"context"
)

const setOwnerIDNullInFiles = `-- name: SetOwnerIDNullInFiles :exec
UPDATE files SET
  owner_id = NULL
WHERE owner_id = $1
`

func (q *Queries) SetOwnerIDNullInFiles(ctx context.Context, ownerID int32) error {
	_, err := q.db.Exec(ctx, setOwnerIDNullInFiles, ownerID)
	return err
}
