// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: message_status.sql

package db

import (
	"context"
)

const deleteMessStatusUser = `-- name: DeleteMessStatusUser :exec
DELETE FROM message_status
WHERE user_id = $1
`

func (q *Queries) DeleteMessStatusUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteMessStatusUser, userID)
	return err
}

const updateMessStatusUser = `-- name: UpdateMessStatusUser :exec
UPDATE message_status SET
  user_id = NULL
WHERE user_id = $1
`

func (q *Queries) UpdateMessStatusUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, updateMessStatusUser, userID)
	return err
}
