// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: messages.sql

package db

import (
	"context"
)

const setSenderIDNullInMess = `-- name: SetSenderIDNullInMess :exec
UPDATE messages SET
  sender_id = NULL
WHERE sender_id = $1
`

func (q *Queries) SetSenderIDNullInMess(ctx context.Context, senderID int32) error {
	_, err := q.db.Exec(ctx, setSenderIDNullInMess, senderID)
	return err
}
