// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Url       string           `json:"url"`
	OwnerID   pgtype.Int4      `json:"owner_id"`
	RoomID    pgtype.Int4      `json:"room_id"`
	MessageID pgtype.Int4      `json:"message_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID        int32            `json:"id"`
	Content   string           `json:"content"`
	SenderID  pgtype.Int4      `json:"sender_id"`
	RoomID    pgtype.Int4      `json:"room_id"`
	PinnedAt  pgtype.Timestamp `json:"pinned_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type MessageStatus struct {
	UserID    int32       `json:"user_id"`
	MessageID int32       `json:"message_id"`
	Status    pgtype.Text `json:"status"`
}

type RefreshToken struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Room struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	CreatorID pgtype.Int4      `json:"creator_id"`
}

type RoomUser struct {
	RoomID int32 `json:"room_id"`
	UserID int32 `json:"user_id"`
}

type User struct {
	ID             int32            `json:"id"`
	Name           string           `json:"name"`
	PhoneNumber    string           `json:"phone_number"`
	Dob            pgtype.Date      `json:"dob"`
	Address        pgtype.Text      `json:"address"`
	Email          string           `json:"email"`
	Avatar         pgtype.Text      `json:"avatar"`
	Password       string           `json:"password"`
	ActivationCode pgtype.Text      `json:"activation_code"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	RoleID         pgtype.Int4      `json:"role_id"`
}
