// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefrTokenByUserId = `-- name: DeleteRefrTokenByUserId :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefrTokenByUserId(ctx context.Context, userID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteRefrTokenByUserId, userID)
	return err
}
