// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: rooms.sql

package db

import (
	"context"
)

const setCreatorIDNullInRoom = `-- name: SetCreatorIDNullInRoom :exec
UPDATE rooms SET
  creator_id = NULL
WHERE creator_id = $1
`

func (q *Queries) SetCreatorIDNullInRoom(ctx context.Context, creatorID int32) error {
	_, err := q.db.Exec(ctx, setCreatorIDNullInRoom, creatorID)
	return err
}
