// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: room_users.sql

package db

import (
	"context"
)

const deleteRoomUserByUserId = `-- name: DeleteRoomUserByUserId :exec
DELETE FROM room_users
WHERE user_id = $1
`

func (q *Queries) DeleteRoomUserByUserId(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteRoomUserByUserId, userID)
	return err
}

const setUserIDNullInRoomUser = `-- name: SetUserIDNullInRoomUser :exec
UPDATE room_users SET
  user_id = NULL
WHERE user_id = $1
`

func (q *Queries) SetUserIDNullInRoomUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, setUserIDNullInRoomUser, userID)
	return err
}
