// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setCreatorIDNullInRoom = `-- name: SetCreatorIDNullInRoom :exec
UPDATE rooms SET
  creator_id = NULL
WHERE creator_id = $1
`

func (q *Queries) SetCreatorIDNullInRoom(ctx context.Context, creatorID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, setCreatorIDNullInRoom, creatorID)
	return err
}
