services:
  admin-service:
    image: tumuaxuan/user-service
    container_name: user-service
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chat_app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=phamtantudn3
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  admin-crud-user:
    build:
      context: ../admin-crud-user
      dockerfile: admin.crud.user.Dockerfile  
    environment:
      - DATABASE_NAME=chat_app
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=phamtantudn3
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - "8085:8085"
    networks:
      - app-network

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phamtantudn3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
