services:
  chatapp.message:
    image: ${DOCKER_REGISTRY-}chatappmessage
    build:
      context: .
      dockerfile: Services/Message/ChatApp.Message/Dockerfile
  admin-service:
    image: tumuaxuan/admin-service:s1
    container_name: admin-service
    ports:
      - 8080:8080
    restart: on-failure
  admin-crud-user:
    build:
      context: ./Services/admin-crud-user
      dockerfile: admin.crud.user.Dockerfile  
    ports:
      - "8085:8085"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:alpine3.20
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: