services:
  chatapp.message:
    image: ${DOCKER_REGISTRY-}chatappmessage
    build:
      context: .
      dockerfile: Services/Message/ChatApp.Message/Dockerfile
  admin-service:
    image: tumuaxuan/admin-service:s1
    container_name: admin-service
    ports:
      - 8080:8080
    restart: on-failure
